---
title: "MVA_HW_2"
author: "sp2245@scarletmail.rutgers.edu"
date: "02/12/2023"
output: html_document
---
## Import Dataset
```{r}
library(readr)
Bumpus_sparrows <- read_csv("C:/Users/saile/Downloads/Bumpus_sparrows.csv")
Bumpus_sparrows
sparr = Bumpus_sparrows
sparr

```
## Load packages
```{r}
library(lattice)
library(ggplot2)
library(ggridges)
library(ggvis)
library(ggthemes)
library(cowplot)
library(gapminder)
library(gganimate)
library(dplyr)
library(tidyverse)
library(grid)
library(gridExtra)
library(RColorBrewer)

```
## ggplot
```{r}
ggplot(sparr, aes(x=Alar_extent,y=L_beak_head)) + geom_point()

ggplot(sparr, aes(x=Alar_extent,y=L_beak_head)) + facet_wrap(~Survivorship) + geom_point()

ggplot(sparr, aes(x=Total_length, y=L_beak_head)) +geom_point(aes(color=Total_length))

ggplot(sparr, aes(x=Total_length,y=L_humerous)) + xlim(150,170) + geom_point(colour="steelblue", pch=3) + 
  labs(x="Length of the sparrow", y="Length of humerous in sparrows", title="Bumpus_Sparrow Data") 

```

## Bar chart

```{r}
ggplot(sparr, aes(Alar_extent)) + geom_bar(position="stack") 
ggplot(sparr, aes(L_humerous) )+ geom_bar(position="stack") 
ggplot(sparr, aes(L_beak_head)) + facet_grid(.~Survivorship) + geom_bar(position="dodge")
ggplot(sparr, aes(x=Total_length, fill=Survivorship)) + geom_bar()+theme_bw()
```

## Histogram

```{r}
ggplot(sparr, aes(L_humerous))+geom_histogram(bins=10)
ggplot(sparr, aes(L_humerous))+geom_histogram(aes(fill = after_stat(count)))

```

## Regression

```{r}
ggplot(sparr, aes(x=L_keel_sternum, y=L_beak_head)) + geom_point() + geom_smooth(method=lm)
ggplot(sparr, aes(x=Total_length, y=Alar_extent)) + geom_point() + stat_smooth()
ggplot(sparr, aes(x=Total_length, y=L_humerous)) + geom_point() + stat_smooth()

```

## Violin Plot 

```{r}
ggplot(sparr, aes(x=Survivorship, y=Alar_extent)) + geom_violin()
ggplot(sparr, aes(x=Survivorship, y=L_humerous)) + geom_violin()
ggplot(sparr, aes(x=Survivorship, y=L_beak_head)) + geom_violin()
```

## Box Plot

```{r}
ggplot(sparr, aes(x=Survivorship, y=L_keel_sternum)) + geom_boxplot()
ggplot(sparr, aes(x=Survivorship, y=Total_length)) + geom_boxplot() + coord_flip()
```

## Density Plot and ggridges

```{r}
ggplot(sparr, aes(x=L_humerous)) + geom_density() 
ggplot(sparr, aes(x=Total_length, fill=Survivorship, color=Survivorship)) + geom_density() 
ggplot(sparr, aes(x=L_keel_sternum, fill=Survivorship, color=Survivorship)) + geom_density(alpha=0.3, aes(y=..scaled..)) 

ggplot(sparr, aes(x=L_beak_head, y=Survivorship)) + geom_density_ridges() 
ggplot(sparr, aes(x=Alar_extent)) + geom_density() 
ggplot(sparr, aes(x=L_beak_head, y=Survivorship)) + geom_density_ridges() 
```

## Hexbin

```{r}
ggplot(sparr, aes(x=L_keel_sternum, y=Total_length)) + geom_hex() 

```

## Ggthemes

```{r}
# with ggthemes (see also ggsci, ggthemr)
lastplot <- ggplot(sparr, aes(x=Total_length,y=Alar_extent)) + xlim(150,170) + geom_point(aes(color=Survivorship)) + stat_smooth() + 
  labs(x="Total Length of Sparrow", y="Length of humerous", title="Bumpus Sparrows") 

lastplot + theme_bw()
lastplot + theme_cowplot()
lastplot + theme_dark()
lastplot + theme_economist()
lastplot + theme_fivethirtyeight()
lastplot + theme_tufte()
lastplot + theme_wsj()
```

